name = "Greenis Cobblepack"
author = "The Lean Green Porcini Machine"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f84cba8cdbb13c0be132850d123bd65b0ebdb429eedadb4c93ac2a85861086"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.107"
